spring.application.name=backend

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USERNAME}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-exception=false